#!/usr/bin/env bash

set -e

# Generate the AST using the generateAST target
podman build -t lox-generateast:latest --target generateAST .
echo "Generating AST..."
podman run --rm -v $(pwd):/mnt/host lox-generateast:latest

podman build -t lox:latest --target lox .

echo "Starting lox..."
podman run -it -v $(pwd):/mnt/host lox:latest java -jar lox.jar $@
